services:
  app:
    container_name: whatsgo-app
    build: .
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
